apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  50000: "surveillance/ispyagentdvr:50000"
  50001: "surveillance/ispyagentdvr:50001"
  50002: "surveillance/ispyagentdvr:50002"
  50003: "surveillance/ispyagentdvr:50003"
  50004: "surveillance/ispyagentdvr:50004"
  50005: "surveillance/ispyagentdvr:50005"
  50006: "surveillance/ispyagentdvr:50006"
  50007: "surveillance/ispyagentdvr:50007"
  50008: "surveillance/ispyagentdvr:50008"
  50009: "surveillance/ispyagentdvr:50009"
  50010: "surveillance/ispyagentdvr:50010"
  3478: "surveillance/ispyagentdvr:3478"