---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ispyagentdvr
  namespace: surveillance
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
   -  host: agentdvr.{{ public_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ispyagentdvr
                port:
                  name: http
